[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
rand = "0.8.5"
serde = "1.0.209"
serde_derive = "1.0.210"
serde_json = "1.0.128"
